### ISSUE TITLE
TypeError: Object.setPrototypeOf called on null or undefined

### ISSUE THREAD

**Issue by vjpr** [matutter/dockerfilejs#1]
This line is giving me trouble: `require('util').inherits(module.exports, Error);`

Trace with `console.log(module.exports, Error`.

```
{ InstructionError: [Function: InstructionError],
  MissingPropertyError: [Function: MissingPropertyError],
  EmptyArrayError: [Function: EmptyArrayError],
  EmptyStringError: [Function: EmptyStringError],
  PropertyConflictError: [Function: PropertyConflictError] } { [Function: Error]
  captureStackTrace: [Function: captureStackTrace],
  stackTraceLimit: 10,
  prepareStackTrace: [Function: prepareStackTrace] }
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at Object.exports.inherits (util.js:973:10)
    at Object.<anonymous> (/Users/Vaughan/dev-live/dockerer/node_modules/.store/dockerfilejs@1.0.4/_/bin/instruction_error.js:42:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

I am running on Node.js 6.5.0.

**Comment by matutter** [comment]
Thanks for the bug report & info. I'll look into this.

**Comment by matutter** [comment]
[Build with 6.5.0](https://travis-ci.org/matutter/dockerfilejs/jobs/166874485)  [![Build Status](https://travis-ci.org/matutter/dockerfilejs.svg?branch=master)](https://travis-ci.org/matutter/dockerfilejs)
I'll merge and publish the fix to npm in a bit.
